export const products = [
  {
    _id: 1,
    name: "Men Soild T-Shirt",
    brand: "RoadStar",
    img: "",
    alt: "mens T-shirt",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 11,
    size: "M",
    idealFor: "M",
    rating: 3.2,
  },
  {
    _id: 2,
    name: "Women Floral Dress",
    brand: "Zara",
    img: "",
    alt: "womens dress",
    newPrice: 5200,
    oldPrice: 6999,
    discount: 26,
    size: "L",
    idealFor: "F",
    rating: 4.5,
  },
  {
    _id: 3,
    name: "Kids Casual Shorts",
    brand: "H&M",
    img: "",
    alt: "kids shorts",
    newPrice: 1800,
    oldPrice: 2499,
    discount: 28,
    size: "S",
    idealFor: "K",
    rating: 4.0,
  },
  {
    _id: 4,
    name: "Men Slim Fit Jeans",
    brand: "Levis",
    img: "",
    alt: "mens jeans",
    newPrice: 6200,
    oldPrice: 7999,
    discount: 22,
    size: "XL",
    idealFor: "M",
    rating: 4.3,
  },
  {
    _id: 5,
    name: "Women Crop Top",
    brand: "Forever 21",
    img: "",
    alt: "womens crop top",
    newPrice: 2600,
    oldPrice: 3199,
    discount: 19,
    size: "M",
    idealFor: "F",
    rating: 3.9,
  },
  {
    _id: 6,
    name: "Men Leather Jacket",
    brand: "Zara",
    img: "",
    alt: "mens jacket",
    newPrice: 12500,
    oldPrice: 15999,
    discount: 22,
    size: "L",
    idealFor: "M",
    rating: 4.7,
  },
  {
    _id: 7,
    name: "Kids Party Dress",
    brand: "Mothercare",
    img: "",
    alt: "kids party dress",
    newPrice: 4300,
    oldPrice: 5499,
    discount: 21,
    size: "S",
    idealFor: "K",
    rating: 4.1,
  },
  {
    _id: 8,
    name: "Women Ethnic Kurti",
    brand: "Biba",
    img: "",
    alt: "womens kurti",
    newPrice: 3100,
    oldPrice: 3999,
    discount: 23,
    size: "XL",
    idealFor: "F",
    rating: 4.4,
  },
  {
    _id: 9,
    name: "Men Sports Shoes",
    brand: "Nike",
    img: "",
    alt: "mens sports shoes",
    newPrice: 8900,
    oldPrice: 9999,
    discount: 11,
    size: "10",
    idealFor: "M",
    rating: 4.6,
  },
  {
    _id: 10,
    name: "Women Handbag",
    brand: "Gucci",
    img: "",
    alt: "womens handbag",
    newPrice: 22500,
    oldPrice: 27999,
    discount: 19,
    size: "One Size",
    idealFor: "F",
    rating: 4.8,
  },
];
